### ISSUE TITLE
Certain errors kill tape-watch

### ISSUE THREAD

**Issue by jonahx** [rstacruz/tape-watch#19] opened 2016-04-06 18:24 UTC
I'm not exactly sure what's happening, but in most cases tape-watch can recover from syntax and runtime errors, and if you fix the error the tape-watch output continues.  For example, I start tape-watch on this file:

```
var test = require('tape');

test('test addition', function (t) {
  t.equal(1+1, 2, 'one plus one');
  t.end();
});
```
and see:

```
TAP version 13
# test addition
ok 1 one plus one

1..1
# tests 1
# pass  1

# ok
```

then I make the change:

```
test('test addition', function (t) {
  t.equal(1+1, 2.length, 'one plus one');
  t.end();
});
```

and see the additional output:

```
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /Users/jg/Dropbox/node/tape-growl/node_modules/tape-watch/bin/tape-watch:89:5
    at invoke (/Users/jg/Dropbox/node/tape-growl/node_modules/tape-watch/bin/tape-watch:69:10)
    at FSWatcher.<anonymous> (/Users/jg/Dropbox/node/tape-growl/node_modules/tape-watch/bin/tape-watch:47:10)
TAP version 13

1..0
# tests 0
# pass  0

# ok
```
Now I fix the error, so that the file returns to it's original state, and see the additional output:

```
TAP version 13
# test addition
ok 1 one plus one

1..1
# tests 1
# pass  1

# ok
```
Finally, I make an even stranger error, calling length on an undefined variable:

```
test('test addition', function (t) {
  a.length
  t.equal(1+1, 2, 'one plus one');
  t.end();
});
```
and see:

```
TAP version 13
# test addition
ReferenceError: a is not defined
    at Test.<anonymous> (/Users/jg/Dropbox/node/tape-growl/test/test1.js:4:3)
    at Test.bound [as _cb] (/Users/jg/Dropbox/node/tape-growl/node_modules/tape/lib/test.js:61:32)
    at Test.run (/Users/jg/Dropbox/node/tape-growl/node_modules/tape/lib/test.js:80:10)
    at Test.bound [as run] (/Users/jg/Dropbox/node/tape-growl/node_modules/tape/lib/test.js:61:32)
    at Immediate.next [as _onImmediate] (/Users/jg/Dropbox/node/tape-growl/node_modules/tape/lib/results.js:70:15)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

At this point the tape-watch process is cooked.  If I change the file back to its original, correct form, no further output will appear.  Is this something that can be fixed?

**Comment by jgallen23** [comment] 2016-05-21 19:50
I'm having the same issues. @jonahx did you figure out a workaround or did you switch libraries?

**Comment by jonahx** [comment] 2016-05-22 03:17
It's been a bit since I was using this daily, so can't remember 100% but I think I was just restarting manually and never found a good solution, either within tape-watch or via another library.  Lmk if you find either.  I will probably revisit this within the next couple weeks, so will do the same.

**Comment by rstacruz** [comment] 2016-05-22 13:20
I can use some help figuring out a way around this. It likely involves
capturing uncaught exceptions somehow.

**Comment by pimhooghiemstra** [comment] 2016-05-27 13:54
@rstacruz I ran into this issue also. I Just began with testing and am using tape. I was looking for a way to watch the changes and rerun the tests and found tape-watch. I am running it like:
`"testnew": "babel-node ./node_modules/.bin/tape-watch ./scripts/test/*-test.js"`
and it works well up to the point that I created an error in my component. as jonahx pointed out, my terminal seems to freeze. Quiting (Ctrl + c) and restarting is a workaround, but not very nice.

In my case, the error is a TypeError:

`# ok
TAP version 13
# Finished component
# -- Check score of player 1
# ++++ The outermost div should have a class named overlay-container
ok 1 (unnamed assert)
# ++++ The first player is called lim
TypeError: Cannot read property 'children' of undefined
    at Test.<anonymous> (/Applications/MAMP/htdocs/Local_dev/JS_Study/REACT/Darts/TacticsComponentTest/scripts/test/finished-test.js:50:48)
    at Test.bound [as _cb] (/Applications/MAMP/htdocs/Local_dev/JS_Study/REACT/Darts/TacticsComponentTest/node_modules/tape/lib/test.js:61:32)
    at Test.run (/Applications/MAMP/htdocs/Local_dev/JS_Study/REACT/Darts/TacticsComponentTest/node_modules/tape/lib/test.js:80:10)
    at Test.bound [as run] (/Applications/MAMP/htdocs/Local_dev/JS_Study/REACT/Darts/TacticsComponentTest/node_modules/tape/lib/test.js:61:32)
    at Test._end (/Applications/MAMP/htdocs/Local_dev/JS_Study/REACT/Darts/TacticsComponentTest/node_modules/tape/lib/test.js:149:11)
    at Test.bound [as _end] (/Applications/MAMP/htdocs/Local_dev/JS_Study/REACT/Darts/TacticsComponentTest/node_modules/tape/lib/test.js:61:32)
    at Test.<anonymous> (/Applications/MAMP/htdocs/Local_dev/JS_Study/REACT/Darts/TacticsComponentTest/node_modules/tape/lib/test.js:148:40)
    at emitNone (events.js:86:13)
    at Test.emit (events.js:185:7)
    at Test.bound [as emit] (/Applications/MAMP/htdocs/Local_dev/JS_Study/REACT/Darts/TacticsComponentTest/node_modules/tape/lib/test.js:61:32)`

Would this help you?

**Comment by rstacruz** [comment] 2016-05-27 14:24
Thanks for the detailed report. I'll have to find some time to investigate.
PRs are also very welcome.

**Comment by rstacruz** [comment] 2016-05-27 15:32
I'm having trouble reproducing this bug. Can those of you who reported bugs also report:

- Node.js version
- Other things you're using with it (like tape-growl)

**Comment by pimhooghiemstra** [comment] 2016-05-27 15:56
My current node --version is 6.1.0
I am not using tape-growl.

My small app is available on Bitbucket if you like to examine further...
https://bitbucket.org/plintsites/tacticscomponenttest

**Comment by rstacruz** [comment] 2016-05-27 16:08
Can you try with v2.0.2, @pimhooghiemstra?

**Comment by pimhooghiemstra** [comment] 2016-05-27 17:17
@rstacruz that version doesn;t seem to exist or am I wrong? Just checked it here https://nodejs.org/en/download/releases/ and was trying to install it using the npm package 'n'.

**Comment by jonahx** [comment] 2016-06-14 20:23
So, not a solution, but as a workaround for now i've been using tape-catch, basically a drop-in replacement for tape, which converts syntax errors into TAP format.  If you still see problems which are killing that process, you can just revert to using nodemon:

`nodemon -x 'tape test/*.js | tape-growl | tap-spec`

This solution has been completely robust for me, and with minimal extra time over tape-watch, albeit on a small set of tests so far.  My growl notifications are popping up in 300-500ms.

**Comment by rstacruz** [comment] 2016-06-18 18:28
@pimhooghiemstra, i meant tape-watch@2.0.2 :)

**Comment by rstacruz** [comment] 2016-08-18 10:07
Huzzah! v2.2.1 now fixes this. It turns out `unhandledException`s stops tape-watch from invoking tape again. Fixed now.

**Closed by rstacruz** 2016-08-18 10:07 UTC

**Comment by pimhooghiemstra** [comment] 2016-08-18 11:03
great! when I have time I will have a look. Cheers!

2016-08-18 12:07 GMT+02:00 Rico Sta. Cruz <notifications@github.com>:
